using System;
using System.Collections.Generic;

namespace SmartDesktop.Core.Services;

/// <summary>
/// Static class containing predefined mappings of applications to categories.
/// Designed for easy expansion and future server-side updates.
/// </summary>
public static class AppCategoryMappings
{
    /// <summary>
    /// Maps application names (lowercase, partial match) to their categories.
    /// </summary>
    public static readonly Dictionary<string, string> AppToCategory = new(StringComparer.OrdinalIgnoreCase)
    {
        // === Productivity ===
        { "word", "Productivity" },
        { "excel", "Productivity" },
        { "powerpoint", "Productivity" },
        { "onenote", "Productivity" },
        { "outlook", "Productivity" },
        { "notion", "Productivity" },
        { "todoist", "Productivity" },
        { "evernote", "Productivity" },
        { "trello", "Productivity" },
        { "asana", "Productivity" },
        { "monday", "Productivity" },
        { "clickup", "Productivity" },
        { "obsidian", "Productivity" },
        { "roam", "Productivity" },
        { "google docs", "Productivity" },
        { "google sheets", "Productivity" },
        { "google slides", "Productivity" },
        { "libreoffice", "Productivity" },
        { "openoffice", "Productivity" },
        { "wps office", "Productivity" },
        { "airtable", "Productivity" },
        { "coda", "Productivity" },
        
        // === Development ===
        { "visual studio", "Development" },
        { "vs code", "Development" },
        { "vscode", "Development" },
        { "code", "Development" },
        { "github", "Development" },
        { "git", "Development" },
        { "android studio", "Development" },
        { "xcode", "Development" },
        { "intellij", "Development" },
        { "pycharm", "Development" },
        { "webstorm", "Development" },
        { "rider", "Development" },
        { "datagrip", "Development" },
        { "eclipse", "Development" },
        { "netbeans", "Development" },
        { "sublime", "Development" },
        { "atom", "Development" },
        { "notepad++", "Development" },
        { "postman", "Development" },
        { "insomnia", "Development" },
        { "docker", "Development" },
        { "terminal", "Development" },
        { "powershell", "Development" },
        { "cmd", "Development" },
        { "command prompt", "Development" },
        { "wsl", "Development" },
        { "ubuntu", "Development" },
        { "putty", "Development" },
        { "filezilla", "Development" },
        { "sourcetree", "Development" },
        { "gitkraken", "Development" },
        { "fork", "Development" },
        { "sql server", "Development" },
        { "mysql", "Development" },
        { "postgresql", "Development" },
        { "mongodb", "Development" },
        { "dbeaver", "Development" },
        { "azure", "Development" },
        { "aws", "Development" },
        { "cursor", "Development" },
        { "windsurf", "Development" },
        
        // === Social & Communication ===
        { "whatsapp", "Social" },
        { "telegram", "Social" },
        { "discord", "Social" },
        { "slack", "Social" },
        { "teams", "Social" },
        { "zoom", "Social" },
        { "skype", "Social" },
        { "messenger", "Social" },
        { "signal", "Social" },
        { "viber", "Social" },
        { "line", "Social" },
        { "wechat", "Social" },
        { "twitter", "Social" },
        { "x ", "Social" },
        { "facebook", "Social" },
        { "instagram", "Social" },
        { "tiktok", "Social" },
        { "snapchat", "Social" },
        { "linkedin", "Social" },
        { "reddit", "Social" },
        { "pinterest", "Social" },
        { "tumblr", "Social" },
        { "google meet", "Social" },
        { "webex", "Social" },
        
        // === Media & Entertainment ===
        { "spotify", "Media" },
        { "vlc", "Media" },
        { "netflix", "Media" },
        { "youtube", "Media" },
        { "prime video", "Media" },
        { "amazon video", "Media" },
        { "disney", "Media" },
        { "hbo", "Media" },
        { "hulu", "Media" },
        { "apple music", "Media" },
        { "itunes", "Media" },
        { "media player", "Media" },
        { "groove", "Media" },
        { "winamp", "Media" },
        { "foobar", "Media" },
        { "plex", "Media" },
        { "kodi", "Media" },
        { "photos", "Media" },
        { "gallery", "Media" },
        { "irfanview", "Media" },
        { "xnview", "Media" },
        { "picasa", "Media" },
        { "audacity", "Media" },
        { "obs", "Media" },
        { "streamlabs", "Media" },
        { "handbrake", "Media" },
        { "mpv", "Media" },
        { "potplayer", "Media" },
        { "mpc-hc", "Media" },
        { "kmplayer", "Media" },
        
        // === Games ===
        { "steam", "Games" },
        { "epic games", "Games" },
        { "origin", "Games" },
        { "ubisoft", "Games" },
        { "uplay", "Games" },
        { "battle.net", "Games" },
        { "battlenet", "Games" },
        { "blizzard", "Games" },
        { "gog galaxy", "Games" },
        { "gog", "Games" },
        { "xbox", "Games" },
        { "playstation", "Games" },
        { "ea app", "Games" },
        { "rockstar", "Games" },
        { "riot", "Games" },
        { "league of legends", "Games" },
        { "valorant", "Games" },
        { "minecraft", "Games" },
        { "roblox", "Games" },
        { "fortnite", "Games" },
        { "nvidia geforce", "Games" },
        { "geforce", "Games" },
        { "razer", "Games" },
        { "logitech g", "Games" },
        { "msi afterburner", "Games" },
        { "game bar", "Games" },
        
        // === Browsers ===
        { "chrome", "Browsers" },
        { "firefox", "Browsers" },
        { "edge", "Browsers" },
        { "opera", "Browsers" },
        { "brave", "Browsers" },
        { "safari", "Browsers" },
        { "vivaldi", "Browsers" },
        { "tor", "Browsers" },
        { "arc", "Browsers" },
        { "chromium", "Browsers" },
        
        // === Utilities ===
        { "calculator", "Utilities" },
        { "notepad", "Utilities" },
        { "clock", "Utilities" },
        { "settings", "Utilities" },
        { "control panel", "Utilities" },
        { "task manager", "Utilities" },
        { "file explorer", "Utilities" },
        { "explorer", "Utilities" },
        { "snipping tool", "Utilities" },
        { "snip & sketch", "Utilities" },
        { "paint", "Utilities" },
        { "wordpad", "Utilities" },
        { "7-zip", "Utilities" },
        { "winrar", "Utilities" },
        { "winzip", "Utilities" },
        { "ccleaner", "Utilities" },
        { "everything", "Utilities" },
        { "teracopy", "Utilities" },
        { "f.lux", "Utilities" },
        { "lightshot", "Utilities" },
        { "greenshot", "Utilities" },
        { "sharex", "Utilities" },
        { "autohotkey", "Utilities" },
        { "quicklook", "Utilities" },
        { "powertoys", "Utilities" },
        { "clipboard", "Utilities" },
        { "ditto", "Utilities" },
        
        // === Security & VPN ===
        { "vpn", "Security" },
        { "nordvpn", "Security" },
        { "expressvpn", "Security" },
        { "protonvpn", "Security" },
        { "surfshark", "Security" },
        { "windscribe", "Security" },
        { "antivirus", "Security" },
        { "malwarebytes", "Security" },
        { "avast", "Security" },
        { "avg", "Security" },
        { "norton", "Security" },
        { "kaspersky", "Security" },
        { "bitdefender", "Security" },
        { "windows defender", "Security" },
        { "windows security", "Security" },
        { "keepass", "Security" },
        { "1password", "Security" },
        { "lastpass", "Security" },
        { "bitwarden", "Security" },
        { "dashlane", "Security" },
        { "authy", "Security" },
        
        // === Creative & Design ===
        { "photoshop", "Creative" },
        { "illustrator", "Creative" },
        { "premiere", "Creative" },
        { "after effects", "Creative" },
        { "lightroom", "Creative" },
        { "indesign", "Creative" },
        { "figma", "Creative" },
        { "sketch", "Creative" },
        { "canva", "Creative" },
        { "gimp", "Creative" },
        { "inkscape", "Creative" },
        { "blender", "Creative" },
        { "davinci resolve", "Creative" },
        { "capcut", "Creative" },
        { "filmora", "Creative" },
        { "corel", "Creative" },
        { "affinity", "Creative" },
        { "procreate", "Creative" },
        { "krita", "Creative" },
        { "aseprite", "Creative" },
        { "clip studio", "Creative" },
        { "paint tool sai", "Creative" },
        { "maya", "Creative" },
        { "3ds max", "Creative" },
        { "cinema 4d", "Creative" },
        { "zbrush", "Creative" },
        { "substance", "Creative" },
        
        // === Education ===
        { "duolingo", "Education" },
        { "khan academy", "Education" },
        { "coursera", "Education" },
        { "udemy", "Education" },
        { "quizlet", "Education" },
        { "anki", "Education" },
        { "brilliant", "Education" },
        { "grammarly", "Education" },
        { "wolfram", "Education" },
        { "mathway", "Education" },
        { "photomath", "Education" },
        { "mendeley", "Education" },
        { "zotero", "Education" },
        { "endnote", "Education" },
        
        // === Finance ===
        { "quickbooks", "Finance" },
        { "mint", "Finance" },
        { "ynab", "Finance" },
        { "personal capital", "Finance" },
        { "robinhood", "Finance" },
        { "coinbase", "Finance" },
        { "binance", "Finance" },
        { "paypal", "Finance" },
        { "venmo", "Finance" },
        { "cash app", "Finance" },
        { "banking", "Finance" },
        { "bank", "Finance" },
        
        // === System & Hardware ===
        { "bios", "System" },
        { "driver", "System" },
        { "cpu-z", "System" },
        { "gpu-z", "System" },
        { "hwinfo", "System" },
        { "speccy", "System" },
        { "crystaldisk", "System" },
        { "aida64", "System" },
        { "device manager", "System" },
        { "disk management", "System" },
        { "defragment", "System" },
        { "partition", "System" },
        { "macrium", "System" },
        { "acronis", "System" },
    };

    /// <summary>
    /// Maps file extensions to their categories.
    /// </summary>
    public static readonly Dictionary<string, string> ExtensionToCategory = new(StringComparer.OrdinalIgnoreCase)
    {
        // Documents
        { ".pdf", "Documents" },
        { ".doc", "Documents" },
        { ".docx", "Documents" },
        { ".txt", "Documents" },
        { ".rtf", "Documents" },
        { ".odt", "Documents" },
        { ".xls", "Documents" },
        { ".xlsx", "Documents" },
        { ".ppt", "Documents" },
        { ".pptx", "Documents" },
        { ".csv", "Documents" },
        { ".md", "Documents" },
        { ".epub", "Documents" },
        
        // Images
        { ".jpg", "Images" },
        { ".jpeg", "Images" },
        { ".png", "Images" },
        { ".gif", "Images" },
        { ".bmp", "Images" },
        { ".svg", "Images" },
        { ".webp", "Images" },
        { ".ico", "Images" },
        { ".tiff", "Images" },
        { ".tif", "Images" },
        { ".psd", "Images" },
        { ".ai", "Images" },
        { ".raw", "Images" },
        { ".heic", "Images" },
        
        // Videos
        { ".mp4", "Videos" },
        { ".avi", "Videos" },
        { ".mkv", "Videos" },
        { ".mov", "Videos" },
        { ".wmv", "Videos" },
        { ".flv", "Videos" },
        { ".webm", "Videos" },
        { ".m4v", "Videos" },
        { ".mpeg", "Videos" },
        { ".mpg", "Videos" },
        
        // Audio
        { ".mp3", "Audio" },
        { ".wav", "Audio" },
        { ".flac", "Audio" },
        { ".aac", "Audio" },
        { ".ogg", "Audio" },
        { ".wma", "Audio" },
        { ".m4a", "Audio" },
        { ".aiff", "Audio" },
        
        // Code
        { ".cs", "Code" },
        { ".py", "Code" },
        { ".js", "Code" },
        { ".ts", "Code" },
        { ".java", "Code" },
        { ".cpp", "Code" },
        { ".c", "Code" },
        { ".h", "Code" },
        { ".hpp", "Code" },
        { ".html", "Code" },
        { ".css", "Code" },
        { ".scss", "Code" },
        { ".json", "Code" },
        { ".xml", "Code" },
        { ".yaml", "Code" },
        { ".yml", "Code" },
        { ".php", "Code" },
        { ".rb", "Code" },
        { ".go", "Code" },
        { ".rs", "Code" },
        { ".swift", "Code" },
        { ".kt", "Code" },
        { ".sql", "Code" },
        { ".sh", "Code" },
        { ".ps1", "Code" },
        { ".bat", "Code" },
        
        // Archives
        { ".zip", "Archives" },
        { ".rar", "Archives" },
        { ".7z", "Archives" },
        { ".tar", "Archives" },
        { ".gz", "Archives" },
        { ".bz2", "Archives" },
        { ".iso", "Archives" },
        
        // Executables & Installers
        { ".exe", "Apps" },
        { ".msi", "Apps" },
        { ".lnk", "Apps" },  // Shortcuts
        { ".url", "Apps" },  // Web shortcuts
        { ".appx", "Apps" },
        { ".msix", "Apps" },
    };

    /// <summary>
    /// Related category groups for fallback suggestions.
    /// When categories are mixed, these help determine broader groupings.
    /// </summary>
    public static readonly Dictionary<string, string[]> RelatedCategories = new()
    {
        { "Tools", new[] { "Utilities", "System", "Security" } },
        { "Work", new[] { "Productivity", "Finance", "Documents" } },
        { "Entertainment", new[] { "Media", "Games" } },
        { "Internet", new[] { "Browsers", "Social" } },
        { "Learning", new[] { "Education", "Documents" } },
        { "Design", new[] { "Creative", "Images" } },
    };
}
